---
site_name: Waldiez Runner
site_url: https://waldiez.github.io/runner/
repo_name: waldiez/runner
repo_url: https://github.com/waldiez/runner
edit_uri_template: "blob/main/docs/{path}"
copyright: >
  Copyright &copy; 2025 Waldiez & Contributors

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom-light
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom-dark
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    # - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    repo: material/git
  logo: static/images/logo.svg
  favicon: static/favicon.ico
  include_sidebar: false

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # yamllint disable
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          # yamllint enable
  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

extra_css:
  - static/css/main.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  # - Architecture: architecture.md
  # - API:
  #     - REST & WebSocket: api.md
  #     - Clients & Auth: clients.md
  #     - Tasks: tasks.md
  #     - Live WebSocket Chat: websocket.md
  # - Deployment:
  #     - Overview: deployment/index.md
  #     - Docker & Compose: deployment/docker.md
  #     - Production: deployment/production.md
  #     - Cloud Storage: deployment/cloud.md
  # - Configuration: configuration.md
  # - Contributing: contributing.md
  # - Changelog: changelog.md
