---
site_name: Waldiez Runner
site_url: https://waldiez.github.io/runner/
repo_name: waldiez/runner
repo_url: https://github.com/waldiez/runner
edit_uri_template: "blob/main/docs/{path}"
copyright: >
  Copyright &copy; 2025 Waldiez & Contributors

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: custom-light
      accent: blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: custom-dark
      accent: blue
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # - announce.dismiss
    # - content.action.edit
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    # - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
  icon:
    repo: material/git
  logo: static/images/logo.svg
  favicon: static/favicon.ico
  include_sidebar: false

markdown_extensions:
  - toc:
      permalink: true
      baselevel: 2
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - codehilite
  - extra
  - mdx_truly_sane_lists
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # fmt: off
          # yamllint disable
          format: !!python/name:mermaid2.fence_mermaid_custom
          # yamllint enable
          # fmt: on

  - pymdownx.tabbed:
      alternate_style: true
  - mdx_include:
      base_path: docs

extra_css:
  - static/css/main.css

plugins:
  - search:
      lang: en
  - mermaid2
  - minify_html
  - macros
  - autorefs
  - privacy
  - mkdocs-jupyter
  - mkdocstrings:
      enabled: true
      default_handler: python
      handlers:
        python:
          paths: [.]
          import:
            - url: https://docs.python.org/3/objects.inv
              domains: [std, py]
            - https://typing-extensions.readthedocs.io/en/latest/objects.inv
          options:
            filters:
              - "!^_"
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            docstring_style: numpy
            show_submodules: true
            show_root_heading: false
            show_signature_annotations: true
            show_signature: true
            signature_crossrefs: true
            show_source: true
            group_by_category: false
            show_category_heading: true
            inherited_members: false
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Architecture: architecture.md
  - API:
      - Clients & Auth: clients.md
      - Tasks: tasks.md
      - WebSocket: websocket.md
      - Examples:
          - Task Demo: examples/task_demo.ipynb
          # - Deployment:
          #     - Overview: deployment/index.md
          #     - Docker & Compose: deployment/docker.md
          #     - Production: deployment/production.md
          #     - Cloud Storage: deployment/cloud.md
          # - Configuration: configuration.md
          # - Contributing: contributing.md
          # - Reference (mkdocstrings)
