# SPDX-License-Identifier: Apache-2.0.
# Copyright (c) 2024 - 2025 Waldiez and contributors.

"""add input_timeout

Revision ID: 343db4e146c5
Revises: 6fb95fce068f
Create Date: 2025-04-01 08:56:17.168724+00:00
"""

# flake8: noqa
# pylint: skip-file
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "343db4e146c5"
down_revision: Union[str, None] = "6fb95fce068f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("input_timeout", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "input_timeout")
    # ### end Alembic commands ###
