# SPDX-License-Identifier: Apache-2.0.
# Copyright (c) 2024 - 2025 Waldiez and contributors.

"""update client model

Revision ID: c8d44162a7c4
Revises: 343db4e146c5
Create Date: 2025-04-19 11:22:01.290940+00:00
"""

# flake8: noqa
# pylint: skip-file
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8d44162a7c4"
down_revision: Union[str, None] = "343db4e146c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("clients", sa.Column("name", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("clients", "name")
    # ### end Alembic commands ###
