---
name: Docs 📚

# yamllint disable rule:truthy
on:
  push:
    branches: [main]
  merge_group:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v6.0.0
        with:
          python-version: 3.12
      - run: python scripts/docs.py before
      - run: mkdocs gh-deploy --config-file mkdocs.yml --force
      - run: python scripts/docs.py after

  deploy-docs:
    name: Deploy Docs to GitHub Pages
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          ref: gh-pages
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4.0.0
        with:
          path: "."
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
